# Generated by Django 5.0.6 on 2024-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=200)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_number', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
