# Generated by Django 5.0.6 on 2024-05-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0004_paramtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
