# Generated by Django 5.0.6 on 2024-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0005_relativechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycurrency',
            name='currency_number',
            field=models.IntegerField(null=True),
        ),
    ]
