# Generated by Django 5.0.6 on 2024-05-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0006_alter_countrycurrency_currency_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrycurrency',
            name='currency_number',
        ),
    ]
